### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ailabnjtech** [devJWSong/gpt2-chatbot-pytorch#6]
Hi! When I run sh **exec_data_load.sh**, the following error occurs. Could you please tell me how to solve it? Looking forward to your reply, thank you very much！

Traceback (most recent call last):
  File "src/data_load.py", line 78, in <module>
    tokenizer = GPT2Tokenizer.from_pretrained(args.model_type)
  File "/home/njtech/conda/envs/pytorch2/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/njtech/conda/envs/pytorch2/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1572, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/njtech/conda/envs/pytorch2/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 167, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by devjwsong** [comment]
Hi. Thank you for your attention to my project.

Unfortunately, in my environment, I cannot reproduce your error. It works totally fine.
I think this might be a version issue.
Could you tell me what version of your Huggingface's Transformers library is?

**Comment by ailabnjtech** [comment]
Transformers == 3.1.0🙏

**Comment by devjwsong** [comment]
I'm afraid that after I changed the version, it still works fine in my environment.

I think this might be due to gpt2 path problem when initializing the tokenizer.
Can you show me the entire script of `exec_data_load.sh`?
And it will be more helpful if you show me the whole `pip list`.

**Comment by ailabnjtech** [comment]
exec_data_load.sh

python src/data_load.py \
    --data_dir="data" \
    --train_prefix="train" \
    --valid_prefix="valid" \
    --train_frac=0.8 \
    --model_type="gpt2"

pip list （I pasted the complete list

absl-py                0.13.0
appdirs                1.4.4
astunparse             1.6.3
audioread              2.1.9
backcall               0.2.0
cached-property        1.5.2
cachetools             4.2.2
certifi                2021.5.30
cffi                   1.14.6
charset-normalizer     2.0.2
click                  8.0.1
cloudpickle            1.6.0
cycler                 0.10.0
cytoolz                0.11.0
dask                   2.17.0
datasets               1.1.0
decorator              5.0.9
dill                   0.3.4
filelock               3.0.12
future                 0.18.2
gast                   0.3.3
google-auth            1.33.1
google-auth-oauthlib   0.4.4
google-pasta           0.2.0
grpcio                 1.39.0
h5py                   2.10.0
idna                   3.2
imageio                2.9.0
importlib-metadata     4.6.1
ipython                7.25.0
ipython-genutils       0.2.0
jedi                   0.18.0
joblib                 1.0.1
Keras                  2.3.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
librosa                0.8.1
llvmlite               0.36.0
Markdown               3.3.4
matplotlib             3.4.2
matplotlib-inline      0.1.2
mkl-fft                1.3.0
mkl-random             1.2.1
mkl-service            2.3.0
multiprocess           0.70.12.2
networkx               2.6.1
numba                  0.53.1
numpy                  1.20.2
oauthlib               3.1.1
olefile                0.46
opt-einsum             3.3.0
packaging              21.0
pandas                 1.3.0
parso                  0.8.2
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.3.1
pip                    21.2.4
pooch                  1.4.0
prompt-toolkit         3.0.19
protobuf               3.17.3
ptyprocess             0.7.0
pyarrow                5.0.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.9.0
pyparsing              2.4.7
python-dateutil        2.8.2
pytz                   2021.1
PyWavelets             1.1.1
PyYAML                 5.4.1
regex                  2021.8.3
requests               2.26.0
requests-oauthlib      1.3.0
resampy                0.2.2
rsa                    4.7.2
sacremoses             0.0.45
scikit-image           0.18.2
scikit-learn           0.24.2
scipy                  1.6.2
sentencepiece          0.1.96
setuptools             52.0.0.post20210125
six                    1.16.0
SoundFile              0.10.3.post1
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.0
tensorflow-estimator   2.2.0
tensorflow-gpu         2.2.0
termcolor              1.1.0
threadpoolctl          2.2.0
tifffile               2021.7.2
tokenizers             0.8.1rc2
toolz                  0.11.1
torch                  1.5.1
torchaudio             0.4.0a0+719bcc7
torchvision            0.5.0
tornado                6.1
tqdm                   4.61.2
traitlets              5.0.5
transformers           3.1.0
typing-extensions      3.10.0.0
urllib3                1.26.6
wcwidth                0.2.5
Werkzeug               2.0.1
wheel                  0.36.2
wrapt                  1.12.1
xxhash                 2.0.2
zipp                   3.5.0


Thanks！！

**Comment by devjwsong** [comment]
I cannot find what the problem is...

But as you can see, the tokenizer class cannot detect the model type string.
So you should print out `args` namespace and check whether `args.model_type` is not None.

Please let me know what the result is.

**Comment by ailabnjtech** [comment]
I have checked that the **args.model_type** is of type str, and it also contains **gpt2**, so I am confused why this problem occurs.
Thank you very much for your help, I will reply to you after this problem is solved.
In fact, I have another problem. After running **exec_data_load.sh**, the program will always stop at **Loading the tokenizer...**
There has been no other reaction for a long time. Do you know what may be causing this situation?

**Comment by devjwsong** [comment]
Hmm that's odd. There is something wrong with the tokenizer class...
I think this is an issue to be handled by the library itself, since I don't have any problem with that.
I'm afraid you should ask to https://github.com/huggingface/transformers.

I will let you know if I find what the problem is.
Thank you.

**Comment by ailabnjtech** [comment]
It should be a problem with the version of the installation package. When I recreated the environment and installed the requirements, the problem was solved.
Thanks again for your attention

**Comment by devjwsong** [comment]
You're welcome. :)
